# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Io.js and Node.js.
#environment:
#  matrix:
#    - MSYS2_ARCH: i686
#      MSYSTEM: MINGW32

environment:
  matrix:
  # node.js
    - nodejs_version: "0.8"
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - nodejs_version: "0.10"
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - nodejs_version: "0.12"
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - nodejs_version: "4"
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - nodejs_version: "5"
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - nodejs_version: "6"
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - nodejs_version: "7"
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - nodejs_version: "8"
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - nodejs_version: "9"
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - nodejs_version: "10"
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64

matrix:
  allow_failures:
    - nodejs_version: "0.8"
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  - IF %nodejs_version% == "0.8" npm config set strict-ssl false
  - IF %nodejs_version% LSS 4 npm -g install npm@2
  - IF %nodejs_version% EQU 5 npm -g install npm@3
  - set PATH=%APPDATA%\npm;%PATH%
  # Typical npm stuff.
  - npm install nan bindings mocha should
  - npm install git-clone mkdirp rimraf
  - node scripts/prepare-build.js
  - node scripts/configure-build.js
  - cd libdvbtee
  - cd libdvbpsi
  - ps: .\bootstrap
  - ps: dir
#  - ps: .\configure.bat --enable-static --with-pic # C:\projects\node-dvbtee
  - cp '%APPVEYOR_BUILD_FOLDER%\appveyor.bat' .
  - '%APPVEYOR_BUILD_FOLDER%\libdvbtee\libdvbpsi\appveyor.bat'
  - cd ..
  - cd ..
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
# build: off
build_script:
  - '%APPVEYOR_BUILD_FOLDER%\appveyor.bat'

# Set build version format here instead of in the admin panel.
version: "{build}"
